#
# Makefile for libnssync
#
# Copyright 2012 Vincent Sanders <vince@netsurf-browser.org>
#
# Released under the MIT License (see COPYING file)

# Sources
DIR_SOURCES := base32.c base64.c hex16.c util.c fetcher.c registration.c storage.c sync.c crypto.c bookmarks.c

include $(NSBUILD)/Makefile.subdir
